# Default values for sportslink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

revisionHistoryLimit: 2
replicaCount: 2
image:
  repository: 637423456584.dkr.ecr.ap-northeast-2.amazonaws.com/sportlink-ecr
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "97db9"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 80
  targetPort: 8080 # Add
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "400m"
    memory: "512Mi"

autoscaling:
  enabled: false

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

podAnnotations: {}
podLabels: {}
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: prod-eks-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: eeeni.store
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:637423456584:certificate/44c21aeb-dd1a-405d-8acf-fb5232ad9538
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  host: eeeni.store
  hosts:
    paths:
      path: /
      pathType: Prefix
  spec:
    ingressClassName: alb
