# Default values for sportslink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

revisionHistoryLimit: 2
replicaCount: 2
image:
  repository: 637423456584.dkr.ecr.ap-northeast-2.amazonaws.com/sportlink-ecr
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "52ff9"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 80
  targetPort: 8080 # Add
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

podAnnotations: {}
podLabels: {}
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: prod-eks-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: sportlink.store
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:637423456584:certificate/44c21aeb-dd1a-405d-8acf-fb5232ad9538
  host: sportlink.store
  hosts:
    paths:
      path: /
      pathType: Prefix
  spec:
    ingressClassName: alb
  tls:
    - hosts:
        - sportlink.store
      secretName: tls-secret
redirectIngress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
