apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-app" (include "sportslink.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sportslink.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sportslink.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sportslink.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
          - name: DB_HOST # DB 엔드포인트
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: db_host
          - name: DB_NAME # DB 이름
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: db_name
          - name: S3_BUCKET # S3 버킷
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: s3_bucket
          - name: REDIS_HOST # Redis 엔드포인트
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: redis_host
          - name: DB_USERNAME # DB user
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_username
          - name: DB_PASSWORD # DB apssword
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_password
          - name: AWS_ACCESS_KEY_ID # S3 연결용 aws access key id
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY # S3 연결용 secret access key
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: aws_secret_access_key