{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" (include "sportslink.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sportslink.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.spec.ingressClassName }}
  defaultBackend:
    service:
      name: {{ printf "%s-service" (include "sportslink.fullname" .) }}
      port:
        number: {{ .Values.service.port }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: {{ .Values.ingress.hosts.paths.pathType }}
        path: {{ .Values.ingress.hosts.paths.path }}
        backend:
          service:
            name: {{ printf "%s-service" (include "sportslink.fullname" .) }}
            port:
              number: {{ .Values.service.port }}
{{- end }}

{{- if .Values.redirectIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssl-redirect
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.redirectIngress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
{{- end }}