apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "sportslink.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sportslink.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "sportslink.selectorLabels" . | nindent 4 }}

# apiVersion: v1
# kind: Service
# metadata:
#   name: release-name-sportslink
#   namespace: stage
#   labels:
#     helm.sh/chart: sportslink-0.1.0
#     app.kubernetes.io/name: sportslink
#     app.kubernetes.io/instance: release-name
#     app.kubernetes.io/version: "1.1.0"
#     app.kubernetes.io/managed-by: Helm
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 8000
#       protocol: TCP
#       name: http
#   selector:
#     app.kubernetes.io/name: sportslink
#     app.kubernetes.io/instance: release-name
